# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-25 07:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('caaring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cab',
            name='cab_admin',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='cab_admin', to=settings.AUTH_USER_MODEL),
        ),
    ]
