# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-25 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caaring', '0002_cab_cab_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AlterField(
            model_name='cab',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
