# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-25 19:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caaring', '0006_auto_20180326_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cab',
            name='size',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(7), django.core.validators.MinValueValidator(3)]),
        ),
    ]
