# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-26 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caaring', '0008_auto_20180326_0209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cab',
            name='dep_date',
            field=models.DateField(help_text='<br />Input in format "YYYY-MM-DD"'),
        ),
        migrations.AlterField(
            model_name='cab',
            name='dep_time',
            field=models.TimeField(help_text='<br />Input in format "hh:mm"'),
        ),
    ]
