# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-26 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caaring', '0009_auto_20180326_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cab',
            name='dep_date',
            field=models.DateField(help_text='Input in format "YYYY-mm-dd"'),
        ),
        migrations.AlterField(
            model_name='cab',
            name='dep_time',
            field=models.TimeField(help_text='Input in format "HH:MM"'),
        ),
    ]
