# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-26 13:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caaring', '0011_auto_20180326_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cab',
            name='name',
            field=models.CharField(max_length=25, unique=True, validators=[django.core.validators.RegexValidator(code='invalid name', message='Field can contain only a-z , A-Z , 0-9 , _ , . , @ , - , + ', regex='^[-.@+\\w]+')]),
        ),
    ]
